<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1566890673360' stop='1566890725648'>
    <name>it should login</name>
    <title>it should login</title>
    <test-cases>
        <test-case start='1566890673360' status='failed' stop='1566890725647'>
            <name>should login</name>
            <title>should login</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='5c9a3592-c71b-4815-bd14-0767447eec99-attachment.png' type='image/png' size='31679'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (/usr/local/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4281:23)
                    at listOnTimeout (internal/timers.js:531:17)
                    at processTimers (internal/timers.js:475:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>